// AUTO-GENERATED BY Weapon Anim Converter — edit the source addon, not this file.
export const WEAPONS = {
  "kotarus:bandage_blackpowder": {
    "slot": "wa_bandageblackpowder",
    "stopExpr": "\"!query.is_item_name_any('slot.weapon.mainhand', 0, 'kotarus:bandage_blackpowder', 'kotarus:bandage_blackpowder_use_skill1')\"",
    "clones": [
      "kotarus:bandage_blackpowder_use_skill1"
    ],
    "consumable": true,
    "loop": {},
    "attacks": [],
    "uses": [
      {
        "state": "use_skill1",
        "anim": "animation.bandage_blackpowder.wrap_body",
        "item": "kotarus:bandage_blackpowder_use_skill1",
        "ticks": 30
      }
    ]
  },

  "kotarus:medkit_blackpowder": {
    "slot": "wa_medkitblackpowder",
    "stopExpr": "\"!query.is_item_name_any('slot.weapon.mainhand', 0, 'kotarus:medkit_blackpowder', 'kotarus:medkit_blackpowder_use_skill1')\"",
    "clones": [
      "kotarus:medkit_blackpowder_use_skill1"
    ],
    "consumable": false,
    "loop": {},
    "attacks": [],
    "uses": [
      {
        "state": "use_skill1",
        "anim": "animation.medkit_blackpowder.revive_body",
        "item": "kotarus:medkit_blackpowder_use_skill1",
        "ticks": 70
      }
    ]
  },
  "kotarus:syringe_blackpowder": {
    "slot": "wa_syringeblackpowder",
    "stopExpr": "\"!query.is_item_name_any('slot.weapon.mainhand', 0, 'kotarus:syringe_blackpowder', 'kotarus:syringe_blackpowder_use_skill1')\"",
    "clones": [
      "kotarus:syringe_blackpowder_use_skill1"
    ],
    "consumable": true,
    "loop": {},
    "attacks": [],
    "uses": [
      {
        "state": "use_skill1",
        "anim": "animation.syringe_blackpowder.inject_body",
        "item": "kotarus:syringe_blackpowder_use_skill1",
        "ticks": 30
      }
    ]
  }
};
