// AUTO-GENERATED BY Weapon Anim Converter — do not edit by hand.
import { world, system, ItemStack } from "@minecraft/server";
import { WEAPONS } from "./data.js";
import { runAs } from "../../succubi/cmd.js";

const COMBO_RESET_TICKS = 40;

// itemId (base or hidden clone) -> { baseId, def }
const BY_ITEM = {};
for (const baseId of Object.keys(WEAPONS)) {
  const def = WEAPONS[baseId];
  BY_ITEM[baseId] = { baseId, def };
  for (const cloneId of def.clones) BY_ITEM[cloneId] = { baseId, def };
}

const bodyState = new Map();  // playerId -> anim name currently held on the player
const oneShots = new Map();   // playerId -> { step, lastTick, id, busy, saved }
const lastMove = new Map();   // playerId -> tick of last horizontal movement
const lastLoc = new Map();    // playerId -> { x, y, z }

function cmd(player, text) {
  runAs(player, text); // server-side source: works with cheats off
}

function stopBody(player) {
  const current = bodyState.get(player.id);
  if (current) cmd(player, "stopanimation @s " + current);
  bodyState.delete(player.id);
}

function playBody(player, def, anim) {
  const current = bodyState.get(player.id);
  if (current === anim) return;
  if (current) cmd(player, "stopanimation @s " + current);
  cmd(player, "playanimation @s " + anim + " hold_on 0.0 " + def.stopExpr + " " + def.slot);
  bodyState.set(player.id, anim);
}

function movementState(player) {
  const velocity = player.getVelocity();
  const speed = Math.sqrt(velocity.x * velocity.x + velocity.z * velocity.z);

  const previous = lastLoc.get(player.id);
  const now = player.location;
  let moveTick = lastMove.get(player.id) || 0;
  if (previous) {
    const dx = now.x - previous.x;
    const dz = now.z - previous.z;
    if (dx * dx + dz * dz > 0.004 || speed > 0.10) {
      moveTick = system.currentTick;
      lastMove.set(player.id, moveTick);
    }
  }
  lastLoc.set(player.id, { x: now.x, y: now.y, z: now.z });

  const moving = player.isSprinting || (system.currentTick - moveTick <= 4 && speed > 0.06);
  const falling = !player.isOnGround && velocity.y < -0.1;
  const jumping = player.isJumping || (!player.isOnGround && velocity.y >= -0.1);

  if (player.isSwimming) return ["swim", "idle"];
  if (falling) return ["fall", "idle"];
  if (jumping) return ["jump", "idle"];
  if (player.isSneaking) return ["sneak", moving ? "walk" : "idle"];
  if (player.isSprinting) return ["run", "walk", "idle"];
  if (moving) return ["walk", "idle"];
  return ["idle"];
}

function playOneShot(player, equippable, entry, moves, cycle) {
  if (!moves.length) return;
  const def = entry.def;
  const tick = system.currentTick;

  let combo = oneShots.get(player.id);
  if (!combo || tick - combo.lastTick > COMBO_RESET_TICKS) {
    combo = { step: 0, lastTick: tick, id: 0, busy: false, saved: null };
  } else if (cycle) {
    combo.step = (combo.step + 1) % moves.length;
  }

  const held = equippable.getEquipment("Mainhand");
  if (held && held.typeId === entry.baseId) combo.saved = held;

  combo.lastTick = tick;
  combo.id = (combo.id || 0) + 1;
  combo.busy = true;
  oneShots.set(player.id, combo);

  const move = moves[cycle ? combo.step : 0];
  const runId = combo.id;

  stopBody(player);
  for (const other of moves) cmd(player, "stopanimation @s " + other.anim);
  // Named controller, not the default one. Leaving the controller argument off
  // parks every addon's swing on the same shared runtime controller, so two
  // weapon addons in one world overwrite each other's pose.
  cmd(player, 'playanimation @s ' + move.anim + ' none 0.0 "" ' + def.slot + '_hit');

  if (move.item) {
    try { equippable.setEquipment("Mainhand", new ItemStack(move.item)); } catch (e) { /* full slot */ }
  }

  system.runTimeout(() => {
    // A newer swing already took over; leave its item and timer alone.
    const latest = oneShots.get(player.id);
    if (!latest || latest.id !== runId) return;
    latest.busy = false;
    cmd(player, "stopanimation @s " + move.anim);
    if (!move.item) return;
    try {
      const current = equippable.getEquipment("Mainhand");
      if (current && current.typeId === move.item) {
        if (entry.def.consumable) {
          if (latest.saved && latest.saved.amount > 1) {
            latest.saved.amount -= 1;
            equippable.setEquipment("Mainhand", latest.saved);
          } else {
            equippable.setEquipment("Mainhand", undefined);
          }
        } else {
          equippable.setEquipment("Mainhand", latest.saved || new ItemStack(entry.baseId));
        }
      }
    } catch (e) { /* player left */ }
  }, move.ticks);
}

function heldEntry(equippable) {
  const held = equippable && equippable.getEquipment("Mainhand");
  if (!held) return null;
  const entry = BY_ITEM[held.typeId];
  return entry ? { entry, held } : null;
}

function onHit(entity) {
  if (!entity || entity.typeId !== "minecraft:player") return;
  const equippable = entity.getComponent("minecraft:equippable");
  const found = heldEntry(equippable);
  if (!found) return;
  playOneShot(entity, equippable, found.entry, found.entry.def.attacks, true);
}

try {
  world.afterEvents.entityHitEntity.subscribe((event) => onHit(event.damagingEntity));
} catch (e) { /* older API */ }

try {
  world.afterEvents.entityHitBlock.subscribe((event) => onHit(event.damagingEntity));
} catch (e) { /* older API */ }

try {
  world.afterEvents.itemUse.subscribe((event) => {
    const player = event.source;
    if (!player || player.typeId !== "minecraft:player") return;
    const entry = BY_ITEM[event.itemStack.typeId];
    if (!entry || !entry.def.uses.length) return;
    const equippable = player.getComponent("minecraft:equippable");
    if (!equippable) return;
    playOneShot(player, equippable, entry, entry.def.uses, true);
  });
} catch (e) { /* older API */ }

world.afterEvents.playerSpawn.subscribe((event) => {
  if (!event.player) return;
  bodyState.delete(event.player.id);
  oneShots.delete(event.player.id);
  lastMove.delete(event.player.id);
  lastLoc.delete(event.player.id);
});

system.runInterval(() => {
  for (const player of world.getAllPlayers()) {
    const equippable = player.getComponent("minecraft:equippable");
    if (!equippable) continue;

    const held = equippable.getEquipment("Mainhand");
    const entry = held ? BY_ITEM[held.typeId] : null;

    if (!entry) {
      stopBody(player);
      oneShots.delete(player.id);
      continue;
    }

    const combo = oneShots.get(player.id);

    // Holding a hidden clone. Either the swing is still running, or it got
    // stuck (reload, death, timer lost) and the base item has to come back.
    if (held.typeId !== entry.baseId) {
      if (!combo || !combo.busy) {
        try {
          if (entry.def.consumable) {
            if (combo && combo.saved && combo.saved.amount > 1) {
              combo.saved.amount -= 1;
              equippable.setEquipment("Mainhand", combo.saved);
            } else {
              equippable.setEquipment("Mainhand", undefined);
            }
          } else {
            equippable.setEquipment("Mainhand", (combo && combo.saved) || new ItemStack(entry.baseId));
          }
        } catch (e) { /* full slot */ }
        bodyState.delete(player.id);
      }
      continue;
    }

    if (combo && combo.busy) continue;

    const def = entry.def;
    const wanted = movementState(player).find((name) => def.loop[name]);
    if (wanted) playBody(player, def, def.loop[wanted]);
  }
}, 1);
