# Shop foods, prices (THB, Thai street prices 2026) and what each one does.
# food = hunger points (vanilla, max 20), sat = saturation modifier, thirst = Succubi thirst (max 20; negative = spicy/salty)
# effects: (effect, seconds, amplifier)

EFFECT_TH = {
    "speed": "วิ่งเร็ว", "haste": "ขุด/ทำงานไว", "strength": "แรงขึ้น", "jump_boost": "กระโดดสูง",
    "regeneration": "ฟื้นเลือด", "resistance": "ทนทาน", "fire_resistance": "ทนไฟ", "absorption": "เลือดเสริม",
    "night_vision": "มองในที่มืด", "water_breathing": "หายใจใต้น้ำ", "slow_falling": "ตกช้า", "saturation": "อิ่มนาน",
}
ROMAN = ["", " II", " III"]

# Base models that come from the Food Items pack (key -> geometry file stem, kind, held size)
MODELS = {
    "somtum_plate": ("somtum_plate", "plate", 8.0),
    "larb_plate": ("larb_plate", "plate", 8.0),
    "kratip_rice": ("kratip_rice", "hand", 6.0),
    "kaeng_som": ("kaeng_som", "plate", 7.0),
    "boba_tea": ("boba_tea", "hand", 8.5),
    "fried_chicken_bucket": ("fried_chicken_bucket", "plate", 6.5),
    "moo_ping": ("moo_ping", "hand", 8.5),
    "ramen_bowl": ("ramen_bowl", "plate", 7.5),
    "omelette_rice": ("omelette_rice", "plate", 8.0),
    "fried_insects_plate": ("fried_insects_plate", "plate", 8.0),
    "kratom_bottle": ("kratom_bottle", "hand", 8.0),
}

# Every food item added to the server (id = food:<key>). model = base model; recolor = texture variant recipe name
FOODS = [
    dict(key="somtum_plate", model="somtum_plate", use="eat", price=50, food=6, sat=0.6, thirst=-2,
         effects=[("speed", 30, 0), ("fire_resistance", 30, 0)],
         name="ส้มตำไทย ครกทอง", en="Golden Mortar Som Tam",
         desc="มะละกอสับ ถั่วลิสง มะเขือเทศ เผ็ดจนตัวร้อน"),
    dict(key="somtum_pla_ra", model="somtum_plate", recolor="pla_ra", use="eat", price=55, food=7, sat=0.6, thirst=-3,
         effects=[("strength", 20, 0), ("speed", 30, 0)],
         name="ส้มตำปูปลาร้า", en="Som Tam Pu Pla Ra",
         desc="นัวปลาร้าแท้ แซ่บถึงใจสายอีสาน"),
    dict(key="larb_plate", model="larb_plate", use="eat", price=60, food=8, sat=0.7, thirst=-1,
         effects=[("jump_boost", 30, 0), ("resistance", 20, 0)],
         name="ลาบหมู", en="Larb Moo",
         desc="หมูสับคั่วข้าวคั่ว หอมสมุนไพร"),
    dict(key="kratip_rice", model="kratip_rice", use="eat", price=10, food=4, sat=1.0, thirst=-1,
         effects=[],
         name="ข้าวเหนียว 1 กระติ๊บ", en="Sticky Rice Basket",
         desc="ข้าวเหนียวนึ่งร้อนๆ อยู่ท้องนาน"),
    dict(key="kaeng_som", model="kaeng_som", use="eat", price=70, food=8, sat=0.7, thirst=5,
         effects=[("fire_resistance", 45, 0), ("regeneration", 6, 0)],
         name="แกงส้มใต้", en="Southern Sour Curry",
         desc="น้ำแกงเหลืองจัดจ้าน เปรี้ยวเผ็ดร้อน"),
    dict(key="omelette_rice", model="omelette_rice", use="eat", price=45, food=8, sat=0.8, thirst=-1,
         effects=[("resistance", 30, 0)],
         name="ข้าวไข่เจียว สูตรผู้บัญชาการ", en="Commander's Omelette Rice",
         desc="ไข่เจียวฟูกรอบ ราดซอสพริก อิ่มพร้อมรบ"),
    dict(key="fried_chicken_bucket", model="fried_chicken_bucket", use="eat", price=199, food=20, sat=1.0, thirst=-2,
         effects=[("strength", 60, 0), ("regeneration", 10, 0), ("absorption", 60, 1)],
         name="ถังไก่ทอดสูตรยายน้อย (8 ชิ้น)", en="Grandma Noi's Fried Chicken Bucket",
         desc="ไก่ทอดหนังกรอบ 8 ชิ้น อิ่มเต็มท้อง"),
    dict(key="spicy_chicken_bucket", model="fried_chicken_bucket", recolor="spicy_glaze", use="eat", price=219, food=20, sat=1.0, thirst=-4,
         effects=[("strength", 60, 0), ("fire_resistance", 60, 0), ("speed", 30, 0)],
         name="ถังไก่ทอดซอสเผ็ดเกาหลี (8 ชิ้น)", en="Korean Spicy Chicken Bucket",
         desc="เคลือบซอสโคชูจังเผ็ดหวาน"),
    dict(key="moo_ping", model="moo_ping", use="eat", price=40, food=8, sat=0.8, thirst=-1,
         effects=[("speed", 20, 0)],
         name="หมูปิ้งนมสด 3 ไม้ + ข้าวเหนียว", en="Grilled Pork Skewers + Sticky Rice",
         desc="หมูหมักนมสดย่างเตาถ่าน มื้อเช้าคนไทย"),
    dict(key="ramen_bowl", model="ramen_bowl", use="eat", price=139, food=12, sat=0.8, thirst=6,
         effects=[("haste", 60, 0), ("regeneration", 8, 0)],
         name="ราเมงโชยุ สูตรท่านฮารุโตะ", en="Haruto's Shoyu Ramen",
         desc="น้ำซุปโชยุเคี่ยว 12 ชั่วโมง ไข่ยางมะตูม"),
    dict(key="tomyum_ramen", model="ramen_bowl", recolor="tomyum", use="eat", price=149, food=12, sat=0.8, thirst=4,
         effects=[("haste", 60, 0), ("fire_resistance", 45, 0), ("speed", 20, 0)],
         name="ราเมงต้มยำ สูตรท่านฮารุโตะ", en="Haruto's Tom Yum Ramen",
         desc="ซุปต้มยำน้ำข้น เปรี้ยวเผ็ดแบบไทย"),
    dict(key="tonkotsu_ramen", model="ramen_bowl", recolor="tonkotsu", use="eat", price=159, food=14, sat=0.9, thirst=6,
         effects=[("haste", 60, 0), ("resistance", 45, 0), ("regeneration", 10, 0)],
         name="ราเมงทงคตสึ สูตรท่านฮารุโตะ", en="Haruto's Tonkotsu Ramen",
         desc="ซุปกระดูกหมูข้นขาว เข้มข้นถึงใจ"),
    dict(key="fried_insects_plate", model="fried_insects_plate", use="eat", price=60, food=7, sat=0.7, thirst=-2,
         effects=[("jump_boost", 30, 1), ("strength", 20, 0)],
         name="แมลงทอดรวม สูตรท่านฮารุโตะ", en="Haruto's Mixed Fried Insects",
         desc="จิ้งหรีด หนอนรถด่วน ตั๊กแตน กรอบโปรตีนสูง"),
    dict(key="spicy_insects_plate", model="fried_insects_plate", recolor="tomyum_powder", use="eat", price=70, food=7, sat=0.7, thirst=-3,
         effects=[("jump_boost", 30, 1), ("strength", 20, 0), ("night_vision", 60, 0)],
         name="แมลงทอดคลุกผงต้มยำ", en="Tom Yum Fried Insects",
         desc="คลุกผงต้มยำเผ็ดๆ กรอบจนหยุดไม่ได้"),
    dict(key="boba_tea", model="boba_tea", use="drink", price=45, food=2, sat=0.3, thirst=12,
         effects=[("regeneration", 12, 0)],
         name="ชานมไข่มุก ฮารุโตะ", en="Haruto Bubble Milk Tea",
         desc="ชานมหอมมัน ไข่มุกหนึบ"),
    dict(key="thai_tea_boba", model="boba_tea", recolor="thai_tea", use="drink", price=45, food=2, sat=0.3, thirst=12,
         effects=[("speed", 45, 0)],
         name="ชาไทยไข่มุก", en="Thai Tea with Pearls",
         desc="ชาไทยสีส้มหวานมัน ดื่มแล้วคึก"),
    dict(key="matcha_boba", model="boba_tea", recolor="matcha", use="drink", price=55, food=2, sat=0.3, thirst=12,
         effects=[("absorption", 60, 0), ("regeneration", 8, 0)],
         name="ชาเขียวมัทฉะนมไข่มุก", en="Matcha Milk Tea with Pearls",
         desc="มัทฉะแท้จากอุจิ หอมละมุน"),
    dict(key="cocoa_boba", model="boba_tea", recolor="cocoa", use="drink", price=50, food=3, sat=0.4, thirst=11,
         effects=[("night_vision", 90, 0)],
         name="โกโก้ไข่มุก", en="Cocoa with Pearls",
         desc="โกโก้เข้มข้น ดื่มแล้วตาสว่าง"),
    dict(key="kratom_bottle", model="kratom_bottle", use="drink", price=89, food=2, sat=0.3, thirst=14,
         effects=[("night_vision", 45, 0), ("speed", 35, 1), ("resistance", 35, 0)],
         name="น้ำชาสูตรลับจากท่านฮารุโตะ", en="Haruto's Secret Tea",
         desc="สูตรลับเฉพาะร้าน ใครดื่มก็ฮึกเหิม"),
]
FOOD_BY_KEY = {f["key"]: f for f in FOODS}

# Vending machine items the shops also sell (id -> shop price). Their effects/thirst stay as defined by the server.
SUCCUBI = {
    "water_bottle": ("succubi:drink_water_bottle", 10),
    "coca_cola": ("succubi:drink_coca_cola", 20),
    "pepsi": ("succubi:drink_pepsi", 20),
    "sprite": ("succubi:drink_sprite", 20),
    "green_tea": ("succubi:drink_green_tea", 35),
    "boss_coffee": ("succubi:drink_boss_coffee", 25),
    "redbull": ("succubi:drink_redbull", 25),
}

# Kiosk shops. flag = invisible colour codes in the form title that pick the skin in RP ui/server_form.json
SHOPS = [
    dict(key="somtum", entity="kiosk:somtum_kiosk", flag="§0§9§7§1", title="ร้านส้มตำครกทอง", en="Golden Mortar Som Tam",
         menu=["somtum_plate", "somtum_pla_ra", "larb_plate", "kratip_rice", "s:water_bottle"],
         theme=dict(base=(46, 110, 58), dark=(24, 64, 32), accent=(236, 190, 64), glass=(26, 38, 28), cell=(34, 44, 36))),
    dict(key="chicken", entity="kiosk:chicken_kiosk", flag="§0§9§7§2", title="ร้านไก่ทอดสูตรยายน้อย", en="Grandma Noi's Fried Chicken",
         menu=["fried_chicken_bucket", "spicy_chicken_bucket", "moo_ping", "kratip_rice", "s:coca_cola", "s:water_bottle"],
         theme=dict(base=(200, 36, 40), dark=(120, 16, 22), accent=(250, 244, 232), glass=(40, 22, 22), cell=(48, 32, 32))),
    dict(key="ramen", entity="kiosk:ramen_kiosk", flag="§0§9§7§3", title="ร้านบะหมี่สูตรท่านฮารุโตะ", en="Haruto's Ramen",
         menu=["ramen_bowl", "tomyum_ramen", "tonkotsu_ramen", "s:green_tea", "s:water_bottle"],
         theme=dict(base=(34, 30, 34), dark=(16, 14, 16), accent=(206, 40, 44), glass=(26, 22, 24), cell=(40, 34, 36))),
    dict(key="omelette", entity="kiosk:omelette_kiosk", flag="§0§9§7§4", title="ร้านข้าวไข่เจียว สูตรผู้บัญชาการ", en="Commander's Omelette Rice",
         menu=["omelette_rice", "kaeng_som", "kratip_rice", "s:boss_coffee", "s:pepsi", "s:water_bottle"],
         theme=dict(base=(96, 104, 64), dark=(56, 62, 36), accent=(244, 196, 48), glass=(30, 32, 22), cell=(42, 44, 32))),
    dict(key="fried_insects", entity="kiosk:fried_insects_kiosk", flag="§0§9§7§5", title="ร้านแมลงทอดสูตรท่านฮารุโตะ", en="Haruto's Fried Insects",
         menu=["fried_insects_plate", "spicy_insects_plate", "kratip_rice", "s:redbull", "s:sprite", "s:water_bottle"],
         theme=dict(base=(120, 72, 36), dark=(70, 40, 18), accent=(240, 150, 40), glass=(34, 24, 16), cell=(46, 34, 24))),
    dict(key="haruto_tea", entity="kiosk:haruto_tea_kiosk", flag="§0§9§7§6", title="ร้านน้ำชาฮารุโตะ", en="Haruto Tea House",
         menu=["boba_tea", "thai_tea_boba", "matcha_boba", "cocoa_boba", "kratom_bottle", "s:green_tea"],
         theme=dict(base=(176, 132, 84), dark=(110, 76, 44), accent=(98, 160, 76), glass=(36, 30, 22), cell=(46, 38, 30))),
]
