// GENERATED by tools/v20/packs.py from common.BODY - height -> max HP, speed and hit strength
export const BODY = {"base_cm": 180, "range_cm": 40, "hp_base": 100, "hp_min": 50, "hp_max": 200, "speed_short": 1.15, "speed_tall": 0.87, "damage_short": 0.77, "damage_tall": 1.3, "walk": 0.1};
export function bodyFactor(cm, short, tall) {
  const t = Math.max(-1, Math.min(1, (cm - BODY.base_cm) / BODY.range_cm));
  return t < 0 ? Math.pow(short, -t) : Math.pow(tall, t);
}
// base HP (100) at 180 cm, doubling every 40 cm taller, halving every 40 cm shorter:
// never below half the base, never above double the base, never above 200 (player.json health max)
export function hpFor(cm, base = BODY.hp_base) {
  const hp = base * Math.pow(2, (cm - BODY.base_cm) / BODY.range_cm);
  return Math.min(BODY.hp_max, base * 2, Math.max(Math.round(base / 2), Math.round(hp)));
}
export const speedFor = (cm) => bodyFactor(cm, BODY.speed_short, BODY.speed_tall);
export const damageFor = (cm) => bodyFactor(cm, BODY.damage_short, BODY.damage_tall);
